name: brainstory_gui
description: BrainStory GUI prototype
version: 0.1.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

flutter:
  uses-material-design: true